### ISSUE TITLE
pipeline2/30_speed_accuracy.go Broken pipe

### ISSUE THREAD

**Issue by InkosiZhong** [favyen/otif#2]
I followed the README and typed the following command:
```bash
go run 30_speed_accuracy.go ../../datasets/otif-dataset/ amsterdam ours-simple yolov3-640x352 416_256_-1 '{"Thresholds":[0,0,1,1,1,1,1]}' 10 amsterdam-valid-ours-simple.txt
```
But the routine crashed.
**It seems something is wrong when OTIF tries to use the YOLOv3 model for detection.**
How should I solve this problem or troubleshoot it?
The key error message is shown below.
```log
....... 
frame=  367 fps= 80 q=-0.0 size=  114504kB time=00:00:12.23 bitrate=76677.1kbits/s speed=2.66x    
frame=  337 fps= 74 q=-0.0 size=  105144kB time=00:00:11.23 bitrate=76677.1kbits/s speed=2.46x    
frame=  362 fps= 78 q=-0.0 size=  112944kB time=00:00:12.06 bitrate=76677.1kbits/s speed= 2.6x    
2024-04-16 18:13:27.889017: I tensorflow/stream_executor/platform/default/dso_loader.cc:50] Successfully opened dynamic library libcublas.so.12
[-1 -1] undersized job 28 / 32
[416 256] full job 4 / 4
[416 256] full job 4 / 4
panic: EOF

goroutine 22 [running]:
_/home/inkosizhong/Lab/VideoQuery/otif/pipeline2/lib.(*Yolov3).Detect(0xc000100230, {0xc007048140?, 0x4, 0x2?})
	/home/inkosizhong/Lab/VideoQuery/otif/pipeline2/lib/detect.go:175 +0x44e
_/home/inkosizhong/Lab/VideoQuery/otif/pipeline2/lib.Exec2.func5({0xc000380300, 0x4, 0xc00ce6ef20?})
	/home/inkosizhong/Lab/VideoQuery/otif/pipeline2/lib/exec2a.go:288 +0x279
_/home/inkosizhong/Lab/VideoQuery/otif/pipeline2/lib.Exec2.func2.1()
	/home/inkosizhong/Lab/VideoQuery/otif/pipeline2/lib/exec2a.go:217 +0x110
created by _/home/inkosizhong/Lab/VideoQuery/otif/pipeline2/lib.Exec2.func2
	/home/inkosizhong/Lab/VideoQuery/otif/pipeline2/lib/exec2a.go:181 +0x305
panic: EOF

goroutine 21 [running]:
_/home/inkosizhong/Lab/VideoQuery/otif/pipeline2/lib.(*Yolov3).Detect(0xc000100150, {0xc0001340a0?, 0x4, 0x2?})
	/home/inkosizhong/Lab/VideoQuery/otif/pipeline2/lib/detect.go:175 +0x44e
_/home/inkosizhong/Lab/VideoQuery/otif/pipeline2/lib.Exec2.func5({0xc0001c2000, 0x4, 0xc00ce72f20?})
	/home/inkosizhong/Lab/VideoQuery/otif/pipeline2/lib/exec2a.go:288 +0x279
_/home/inkosizhong/Lab/VideoQuery/otif/pipeline2/lib.Exec2.func2.1()
	/home/inkosizhong/Lab/VideoQuery/otif/pipeline2/lib/exec2a.go:217 +0x110
created by _/home/inkosizhong/Lab/VideoQuery/otif/pipeline2/lib.Exec2.func2
	/home/inkosizhong/Lab/VideoQuery/otif/pipeline2/lib/exec2a.go:181 +0x305
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
av_interleaved_write_frame(): Broken pipe
......
```

**Comment by InkosiZhong** [comment]
Ok, I find the core reason:
```log
Traceback (most recent call last):
  File "yolov3.py", line 19, in <module>
    import darknet
  File "/home/inkosizhong/Lab/VideoQuery/datasets/otif-dataset/darknet-alexey/./darknet.py", line 223, in <module>
    lib = CDLL(os.path.join(
  File "/home/inkosizhong/anaconda3/envs/miris/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ./libdarknet.so: cannot open shared object file: No such file or directory
```
Before `make` the darknet, set `LIBSO=1` in `Makefile` to compile `libdarknet.so`.
Then I get an error for missing `'../../datasets/otif-dataset/yolov3/generic/yolov3-416x256-test.cfg'`
I use the following command and it works well:
```
go run 30_speed_accuracy.go $(pwd)../../datasets/otif-dataset/ amsterdam ours-simple yolov3-640x352 416_256_-1 '{"Thresholds":[0,0,1,1,1,1,1]}' 10 amsterdam-valid-ours-simple.txt
```
